FROM php:8.2-apache

# Activar mod_rewrite (si lo usas)
RUN a2enmod rewrite

# Copiar tu proyecto al servidor Apache
COPY . /var/www/html/

# Establecer permisos
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
